apiVersion: v1
kind: Namespace
metadata:
  name: tomcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - image: tomcat:jre21-temurin-noble
        name: tomcatapp
        ports:
        - containerPort: 8080
