apiVersion: v1
kind: Service
metadata:
  name: cbz-java-svc
  namespace: dev
spec:
  selector:
    app: cbz-java
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32000
